name: 'DPP Validator'
description: 'Validate Digital Product Passports against UNTP schema'
author: 'artiso-ai'
branding:
  icon: 'check-circle'
  color: 'green'

inputs:
  files:
    description: 'File path or glob pattern to validate (e.g., "data/*.json")'
    required: true
  strict:
    description: 'Enable strict JSON Schema validation'
    required: false
    default: 'false'
  fail-on-warning:
    description: 'Fail the action if warnings are found'
    required: false
    default: 'false'
  schema-version:
    description: 'UNTP DPP schema version to validate against'
    required: false
    default: '0.6.1'
  python-version:
    description: 'Python version to use'
    required: false
    default: '3.11'

outputs:
  valid:
    description: 'Whether all files passed validation'
    value: ${{ steps.validate.outputs.valid }}
  error-count:
    description: 'Total number of errors found'
    value: ${{ steps.validate.outputs.error_count }}
  warning-count:
    description: 'Total number of warnings found'
    value: ${{ steps.validate.outputs.warning_count }}

runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install dppvalidator
      shell: bash
      run: pip install dppvalidator[cli]

    - name: Validate DPP files
      id: validate
      shell: bash
      run: |
        set +e

        STRICT_FLAG=""
        if [ "${{ inputs.strict }}" = "true" ]; then
          STRICT_FLAG="--strict"
        fi

        FILES="${{ inputs.files }}"
        TOTAL_ERRORS=0
        TOTAL_WARNINGS=0
        FAILED_FILES=""
        ALL_VALID=true

        echo "## DPP Validation Results" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "| File | Status | Errors | Warnings |" >> $GITHUB_STEP_SUMMARY
        echo "|------|--------|--------|----------|" >> $GITHUB_STEP_SUMMARY

        for file in $FILES; do
          if [ -f "$file" ]; then
            OUTPUT=$(dppvalidator validate "$file" $STRICT_FLAG --format json 2>&1)
            EXIT_CODE=$?

            ERRORS=$(echo "$OUTPUT" | python3 -c "import sys, json; d=json.load(sys.stdin); print(len(d.get('errors', [])))" 2>/dev/null || echo "0")
            WARNINGS=$(echo "$OUTPUT" | python3 -c "import sys, json; d=json.load(sys.stdin); print(len(d.get('warnings', [])))" 2>/dev/null || echo "0")

            TOTAL_ERRORS=$((TOTAL_ERRORS + ERRORS))
            TOTAL_WARNINGS=$((TOTAL_WARNINGS + WARNINGS))

            if [ $EXIT_CODE -eq 0 ]; then
              echo "| \`$file\` | ✅ Valid | $ERRORS | $WARNINGS |" >> $GITHUB_STEP_SUMMARY
            else
              echo "| \`$file\` | ❌ Invalid | $ERRORS | $WARNINGS |" >> $GITHUB_STEP_SUMMARY
              FAILED_FILES="$FAILED_FILES $file"
              ALL_VALID=false
            fi
          fi
        done

        echo "" >> $GITHUB_STEP_SUMMARY
        echo "**Total:** $TOTAL_ERRORS errors, $TOTAL_WARNINGS warnings" >> $GITHUB_STEP_SUMMARY

        echo "valid=$ALL_VALID" >> $GITHUB_OUTPUT
        echo "error_count=$TOTAL_ERRORS" >> $GITHUB_OUTPUT
        echo "warning_count=$TOTAL_WARNINGS" >> $GITHUB_OUTPUT

        if [ "$ALL_VALID" = "false" ]; then
          echo "::error::DPP validation failed for:$FAILED_FILES"
          exit 1
        fi

        if [ "${{ inputs.fail-on-warning }}" = "true" ] && [ $TOTAL_WARNINGS -gt 0 ]; then
          echo "::warning::DPP validation passed with $TOTAL_WARNINGS warning(s)"
          exit 1
        fi

        echo "✅ All DPP files validated successfully"
